name: Secret Scan (Gitleaks)

on:
  push:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks with custom config
        run: |
          docker run --rm -v $PWD:/repo zricethezav/gitleaks:latest \
          detect --source=/repo --config=/repo/gitleaks.toml --verbose